// Generated by CoffeeScript 1.6.2
(function() {
  var assert, formatter;

  formatter = require('../formatter');

  assert = require('assert');

  describe('formatter', function() {
    return describe('#shortenSpaces()', function() {
      return it('should shorten all consecutive spaces into one', function() {
        var formattedLine, originalLine;

        originalLine = 'hello   derek how is  it going?';
        formattedLine = formatter.shortenSpaces(originalLine);
        return assert.strictEqual('hello derek how is it going?', formattedLine);
      });
    });
  });

}).call(this);
