// Generated by CoffeeScript 1.6.2
(function() {
  var Lazy, ONE_SPACE_OPERATORS, TWO_SPACE_OPERATORS, argv, file, filename, formatTwoSpaceOperator, fs, getExtension, notInString, shortenSpaces, _i, _len, _ref;

  Lazy = require('lazy');

  fs = require('fs');

  argv = (require('optimist'))["default"]('tab-width', 2)["default"]('use-space', true).argv;

  TWO_SPACE_OPERATORS = ['=', '+=', '-=', '==', '<=', '>=', '>', "<", '+', '-', '*', '/'];

  ONE_SPACE_OPERATORS = [':', '?', ''];

  notInString = function(index, line) {
    var c, cc, i, ii, subLine, _i, _j, _len, _len1;

    for (i = _i = 0, _len = line.length; _i < _len; i = ++_i) {
      c = line[i];
      if (c === "'" || c === '"') {
        subLine = line.substr(i + 1);
        for (ii = _j = 0, _len1 = subLine.length; _j < _len1; ii = ++_j) {
          cc = subLine[ii];
          if (cc === c) {
            if ((i <= index && index <= ii)) {
              return true;
            } else {
              return notInString(index - (ii + 1), line.substr(ii + 1));
            }
          }
        }
      }
    }
    return false;
  };

  getExtension = function(filename) {
    var i;

    i = filename.lastIndexOf('.');
    if (i < 0) {
      return '';
    } else {
      return filename.substr(i + 1);
    }
  };

  formatTwoSpaceOperator = function(operator, line) {
    var index;

    index = line.indexOf(operator);
    if (notInString(index, line)) {
      if (line[index - 1] !== ' ') {
        return 1 + 1;
      }
    }
  };

  shortenSpaces = function(line) {
    var c, i, newLine, prevChar, _i, _len;

    prevChar = null;
    newLine = '';
    for (i = _i = 0, _len = line.length; _i < _len; i = ++_i) {
      c = line[i];
      if (!(notInString(i, line) && ((c === ' ' && ' ' === prevChar)))) {
        newLine = newLine + c;
      }
      prevChar = c;
    }
    return newLine;
  };

  _ref = argv._;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    filename = _ref[_i];
    if ((getExtension(filename)) !== 'coffee') {
      console.log;
      "" + filename + " doesn't appear to be a CoffeeScript file. Skipping...";
      console.log("Use --force to format it anyway.");
    } else {
      file = '';
      new Lazy(fs.createReadStream(filename, {
        encoding: 'utf8'
      })).lines.forEach(function(line) {
        var newLine, operator, _j, _k, _len1, _len2;

        newLine = line;
        for (_j = 0, _len1 = TWO_SPACE_OPERATORS.length; _j < _len1; _j++) {
          operator = TWO_SPACE_OPERATORS[_j];
          newLine = formatTwoSpaceOperator(operator, newLine);
        }
        for (_k = 0, _len2 = ONE_SPACE_OPERATORS.length; _k < _len2; _k++) {
          operator = ONE_SPACE_OPERATORS[_k];
          newLine = formatOneSpaceOperator(operator, newLine);
        }
        newLine = shortenSpaces(newLine);
        return file += newLine;
      });
    }
  }

  module.exports.shortenSpaces = shortenSpaces;

}).call(this);
